knpu_oauth2_client:
  clients:
    # the key "facebook_main" can be anything, it
    # will create a service: "knpu.oauth2.client.facebook_main"
    facebook_main:
      # this will be one of the supported types
      type: facebook
      client_id: '929615350878626'
      client_secret: '00011da9e2daadf3a5afe3bf3d7e8bd5'
      # the route that you're redirected to after
      # see the controller example below
      redirect_route: connect_facebook_check
      redirect_params: {}
      graph_api_version: v8.0
    google_main:
      # must be "google" - it activates that type!
      type: google
      # add and configure client_id and client_secret in parameters.yml
      client_id: '492254723901-826bkfb708kmj8t7tqhasb88m6g3olr4.apps.googleusercontent.com'
      client_secret: 'lUKClGhFhEVXTsG1aty3NujP'
      # a route name you'll create
      redirect_route: connect_google_check
      redirect_params: {}
      # Optional value for sending access_type parameter. More detail: https://developers.google.com/identity/protocols/OpenIDConnect#authenticationuriparameters
      # access_type: ''
      # Optional value for sending hd parameter. More detail: https://developers.google.com/identity/protocols/OpenIDConnect#hd-param
      # hosted_domain: ''
      # Optional value for additional fields to be requested from the user profile. If set, these values will be included with the defaults. More details: https://developers.google.com/+/web/api/rest/latest/people
      # user_fields: {}
      # whether to check OAuth2 "state": defaults to true
      # use_state: true