<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.8AYGv3u' shared service.

return $this->privates['.service_locator.8AYGv3u'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'ppc' => ['privates', 'JMS\\Payment\\CoreBundle\\PluginController\\EntityPluginController', 'getEntityPluginControllerService.php', true],
    'session' => ['services', 'session', 'getSessionService.php', true],
], [
    'ppc' => '?',
    'session' => '?',
]);
