<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'payment.form.paypal_express_checkout_type' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/form/FormTypeInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/AbstractType.php';
include_once $this->targetDirs[3].'/vendor/jms/payment-paypal-bundle/JMS/Payment/PaypalBundle/Form/ExpressCheckoutType.php';

return $this->privates['payment.form.paypal_express_checkout_type'] = new \JMS\Payment\PaypalBundle\Form\ExpressCheckoutType();
