<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerN2v3hVI\srcApp_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerN2v3hVI/srcApp_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerN2v3hVI.legacy');

    return;
}

if (!\class_exists(srcApp_KernelProdContainer::class, false)) {
    \class_alias(\ContainerN2v3hVI\srcApp_KernelProdContainer::class, srcApp_KernelProdContainer::class, false);
}

return new \ContainerN2v3hVI\srcApp_KernelProdContainer([
    'container.build_hash' => 'N2v3hVI',
    'container.build_id' => '88834765',
    'container.build_time' => 1598056953,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerN2v3hVI');
