#index:
#    path: /
#    controller: App\Controller\DefaultController::index
formule:
  path: /formule
  controller: App\Controller\DefaultController::formule
purchase:
  path: /purchase
  controller: App\Controller\DefaultController::purchase
updateuser:
  path: /updateuser
  controller: App\Controller\DefaultController::updateuser
userProfile:
  path: /userprofile
  controller: App\Controller\DefaultController::userProfile
manageBundle:
  path: /manageBundle
  controller: App\Controller\DefaultController::manageBundle
addBundle:
  path: /addBundle
  controller: App\Controller\FashionBundleController::addBundle
manageProduct:
  path: /manageProducts
  controller: App\Controller\DefaultController::manageProducts
addProduct:
  path: /addProduct
  controller: App\Controller\DefaultController::newProduct
listFashionBoard:
  path: /listFashionBoard
  controller: App\Controller\DefaultController::listFashionBoard
manageFashionBoard:
  path: /manageFashionBoard
  controller: App\Controller\DefaultController::manageFashionBoard
manageOrders:
  path: /manageOrders
  controller: App\Controller\DefaultController::manageOrders
manageQuiz:
  path: /manageQuiz
  controller: App\Controller\DefaultController::manageQuiz
addQuiz:
  path: /addQuiz
  controller: App\Controller\DefaultController::addQuiz
dashboard:
  path: /dashboard
  controller: App\Controller\DefaultController::viewDashboard