<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'knpu.oauth2.client.facebook_main' shared service.

include_once $this->targetDirs[3].'/vendor/knpuniversity/oauth2-client-bundle/src/Client/OAuth2ClientInterface.php';
include_once $this->targetDirs[3].'/vendor/knpuniversity/oauth2-client-bundle/src/Client/OAuth2Client.php';
include_once $this->targetDirs[3].'/vendor/knpuniversity/oauth2-client-bundle/src/Client/Provider/FacebookClient.php';
include_once $this->targetDirs[3].'/vendor/league/oauth2-client/src/Tool/ArrayAccessorTrait.php';
include_once $this->targetDirs[3].'/vendor/league/oauth2-client/src/Tool/GuardedPropertyTrait.php';
include_once $this->targetDirs[3].'/vendor/league/oauth2-client/src/Tool/QueryBuilderTrait.php';
include_once $this->targetDirs[3].'/vendor/league/oauth2-client/src/Provider/AbstractProvider.php';
include_once $this->targetDirs[3].'/vendor/league/oauth2-facebook/src/Provider/Facebook.php';

return $this->services['knpu.oauth2.client.facebook_main'] = new \KnpU\OAuth2ClientBundle\Client\Provider\FacebookClient(($this->privates['knpu.oauth2.provider_factory'] ?? $this->load('getKnpu_Oauth2_ProviderFactoryService.php'))->createProvider('League\\OAuth2\\Client\\Provider\\Facebook', ['clientId' => '929615350878626', 'clientSecret' => '00011da9e2daadf3a5afe3bf3d7e8bd5', 'graphApiVersion' => 'v8.0'], 'connect_facebook_check', [], []), ($this->services['request_stack'] ?? ($this->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())));
