<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'payment.form.choose_payment_method_type' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/form/FormTypeInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/AbstractType.php';
include_once $this->targetDirs[3].'/vendor/jms/payment-core-bundle/JMS/Payment/CoreBundle/Form/ChoosePaymentMethodType.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/DataTransformerInterface.php';
include_once $this->targetDirs[3].'/vendor/jms/payment-core-bundle/JMS/Payment/CoreBundle/Form/Transformer/ChoosePaymentMethodTransformer.php';

$this->privates['payment.form.choose_payment_method_type'] = $instance = new \JMS\Payment\CoreBundle\Form\ChoosePaymentMethodType(($this->privates['JMS\\Payment\\CoreBundle\\PluginController\\EntityPluginController'] ?? $this->load('getEntityPluginControllerService.php')), ['paypal_express_checkout' => 'JMS\\Payment\\PaypalBundle\\Form\\ExpressCheckoutType']);

$instance->setDataTransformer(new \JMS\Payment\CoreBundle\Form\Transformer\ChoosePaymentMethodTransformer());

return $instance;
