<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'JMS\Payment\CoreBundle\Command\GenerateKeyCommand' shared service.

$this->privates['JMS\\Payment\\CoreBundle\\Command\\GenerateKeyCommand'] = $instance = new \JMS\Payment\CoreBundle\Command\GenerateKeyCommand();

$instance->setName('jms_payment_core:generate-key');

return $instance;
