<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Repository\OrderRepository' shared autowired service.

return $this->privates['App\\Repository\\OrderRepository'] = new \App\Repository\OrderRepository(($this->services['doctrine'] ?? $this->getDoctrineService()));
