<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'argument_resolver.service' shared service.

return $this->privates['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\DefaultController::index' => ['privates', '.service_locator.3hxx.mU', 'get_ServiceLocator_3hxx_MUService.php', true],
    'App\\Controller\\DefaultController::paymentCreateAction' => ['privates', '.service_locator.gwf2bnO', 'get_ServiceLocator_Gwf2bnOService.php', true],
    'App\\Controller\\DefaultController::purchase' => ['privates', '.service_locator.8AYGv3u', 'get_ServiceLocator_8AYGv3uService.php', true],
    'App\\Controller\\DefaultController::updateuser' => ['privates', '.service_locator.3hxx.mU', 'get_ServiceLocator_3hxx_MUService.php', true],
    'App\\Controller\\DefaultController:index' => ['privates', '.service_locator.3hxx.mU', 'get_ServiceLocator_3hxx_MUService.php', true],
    'App\\Controller\\DefaultController:paymentCreateAction' => ['privates', '.service_locator.gwf2bnO', 'get_ServiceLocator_Gwf2bnOService.php', true],
    'App\\Controller\\DefaultController:purchase' => ['privates', '.service_locator.8AYGv3u', 'get_ServiceLocator_8AYGv3uService.php', true],
    'App\\Controller\\DefaultController:updateuser' => ['privates', '.service_locator.3hxx.mU', 'get_ServiceLocator_3hxx_MUService.php', true],
], [
    'App\\Controller\\DefaultController::index' => '?',
    'App\\Controller\\DefaultController::paymentCreateAction' => '?',
    'App\\Controller\\DefaultController::purchase' => '?',
    'App\\Controller\\DefaultController::updateuser' => '?',
    'App\\Controller\\DefaultController:index' => '?',
    'App\\Controller\\DefaultController:paymentCreateAction' => '?',
    'App\\Controller\\DefaultController:purchase' => '?',
    'App\\Controller\\DefaultController:updateuser' => '?',
]));
