<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'HWI\Bundle\OAuthBundle\Controller\ConnectController' shared service.

$a = new \HWI\Bundle\OAuthBundle\Security\Http\ResourceOwnerMapLocator();
$a->add('secured_area', ($this->services['hwi_oauth.resource_ownermap.secured_area'] ?? $this->getHwiOauth_ResourceOwnermap_SecuredAreaService()));

$this->services['HWI\\Bundle\\OAuthBundle\\Controller\\ConnectController'] = $instance = new \HWI\Bundle\OAuthBundle\Controller\ConnectController(($this->privates['hwi_oauth.security.oauth_utils'] ?? $this->getHwiOauth_Security_OauthUtilsService()), $a);

$instance->setContainer($this);

return $instance;
