<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'JMS\Payment\CoreBundle\Cryptography\DefusePhpEncryptionService' shared service.

return $this->services['JMS\\Payment\\CoreBundle\\Cryptography\\DefusePhpEncryptionService'] = new \JMS\Payment\CoreBundle\Cryptography\DefusePhpEncryptionService('def00000f3a2e15c4da3cf6053f76dc0e045e6f8253cbb88fe103a46d420dc9f28e31119e578a60c67f0d5c6eb9026a039fdbb33b748979023632c435b42526e34caf225');
