<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'httplug.psr18_client' shared service.

return $this->services['httplug.psr18_client'] = \Http\Discovery\Psr18ClientDiscovery::find();
