<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'hwi_oauth.resource_owner.keycloak' shared service.

return $this->services['hwi_oauth.resource_owner.keycloak'] = new \HWI\Bundle\OAuthBundle\OAuth\ResourceOwner\GenericOAuth2ResourceOwner(new \Http\Client\Common\HttpMethodsClient(($this->services['httplug.client'] ?? $this->load('getHttplug_ClientService.php')), ($this->services['httplug.message_factory'] ?? $this->load('getHttplug_MessageFactoryService.php'))), ($this->privates['security.http_utils'] ?? $this->getSecurity_HttpUtilsService()), ['client_id' => 'symfony', 'client_secret' => '64466fc2-fc1f-4de2-a35e-6953382764e0', 'access_token_url' => 'http://localhost:8080/auth/realms/master/protocol/openid-connect/token', 'authorization_url' => 'http://localhost:8080/auth/realms/master/protocol/openid-connect/auth', 'infos_url' => 'http://localhost:8080/auth/realms/master/protocol/openid-connect/userinfo', 'scope' => 'email openid profile', 'user_response_class' => 'HWI\\Bundle\\OAuthBundle\\OAuth\\Response\\PathUserResponse', 'paths' => ['identifier' => 'id', 'nickname' => 'username', 'realname' => 'fullname'], 'options' => []], 'keycloak', new \HWI\Bundle\OAuthBundle\OAuth\RequestDataStorage\SessionStorage(($this->services['session'] ?? $this->load('getSessionService.php'))));
