<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'hwi_oauth.authentication.provider.oauth.secured_area' shared service.

return $this->privates['hwi_oauth.authentication.provider.oauth.secured_area'] = new \HWI\Bundle\OAuthBundle\Security\Core\Authentication\Provider\OAuthProvider(new \HWI\Bundle\OAuthBundle\Security\Core\User\OAuthUserProvider('App\\Entity\\User', [0 => 'email'], NULL), ($this->services['hwi_oauth.resource_ownermap.secured_area'] ?? $this->getHwiOauth_ResourceOwnermap_SecuredAreaService()), ($this->services['hwi_oauth.user_checker'] ?? ($this->services['hwi_oauth.user_checker'] = new \Symfony\Component\Security\Core\User\UserChecker())), ($this->services['security.token_storage'] ?? ($this->services['security.token_storage'] = new \Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorage())));
