<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'hwi_oauth.authentication.listener.oauth.secured_area' shared service.

$a = ($this->privates['security.http_utils'] ?? $this->getSecurity_HttpUtilsService());
$b = new \Symfony\Component\Security\Http\Authentication\DefaultAuthenticationSuccessHandler($a, []);
$b->setOptions(['login_path' => '/login', 'always_use_default_target_path' => false, 'default_target_path' => '/', 'target_path_parameter' => '_target_path', 'use_referer' => false]);
$b->setProviderKey('secured_area');
$c = ($this->privates['logger'] ?? ($this->privates['logger'] = new \Symfony\Component\HttpKernel\Log\Logger()));

$d = new \Symfony\Component\Security\Http\Authentication\DefaultAuthenticationFailureHandler(($this->services['http_kernel'] ?? $this->getHttpKernelService()), $a, [], $c);
$d->setOptions(['login_path' => '/login', 'failure_path' => '/login', 'failure_forward' => false, 'failure_path_parameter' => '_failure_path']);

$this->privates['hwi_oauth.authentication.listener.oauth.secured_area'] = $instance = new \HWI\Bundle\OAuthBundle\Security\Http\Firewall\OAuthListener(($this->services['security.token_storage'] ?? ($this->services['security.token_storage'] = new \Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorage())), ($this->privates['security.authentication.manager'] ?? $this->getSecurity_Authentication_ManagerService()), ($this->privates['security.authentication.session_strategy'] ?? ($this->privates['security.authentication.session_strategy'] = new \Symfony\Component\Security\Http\Session\SessionAuthenticationStrategy('migrate'))), $a, 'secured_area', $b, $d, ['use_forward' => false, 'check_path' => '/login_check', 'require_previous_session' => false], $c, ($this->services['event_dispatcher'] ?? $this->getEventDispatcherService()));

$instance->setResourceOwnerMap(($this->services['hwi_oauth.resource_ownermap.secured_area'] ?? $this->getHwiOauth_ResourceOwnermap_SecuredAreaService()));
$instance->setCheckPaths([0 => '/login/check-facebook', 1 => '/login/check-google', 2 => '/auth0/callback']);

return $instance;
