<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'HWI\Bundle\OAuthBundle\Controller\RedirectToServiceController' shared service.

return $this->services['HWI\\Bundle\\OAuthBundle\\Controller\\RedirectToServiceController'] = new \HWI\Bundle\OAuthBundle\Controller\RedirectToServiceController(($this->privates['hwi_oauth.security.oauth_utils'] ?? $this->getHwiOauth_Security_OauthUtilsService()), new \HWI\Bundle\OAuthBundle\Util\DomainWhitelist([]), $this->parameters['hwi_oauth.firewall_names'], NULL, false, false);
