<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYIbzkb7\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYIbzkb7/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYIbzkb7.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYIbzkb7\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerYIbzkb7\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'YIbzkb7',
    'container.build_id' => '9581b0ff',
    'container.build_time' => 1598223618,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYIbzkb7');
