<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHl52RMA\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHl52RMA/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHl52RMA.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHl52RMA\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerHl52RMA\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Hl52RMA',
    'container.build_id' => '2ef468e8',
    'container.build_time' => 1598276802,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHl52RMA');
