<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAXj93Cx\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAXj93Cx/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAXj93Cx.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAXj93Cx\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerAXj93Cx\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'AXj93Cx',
    'container.build_id' => 'd0828caf',
    'container.build_time' => 1597455924,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAXj93Cx');
