<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.063kFrc' shared service.

return $this->privates['.service_locator.063kFrc'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\DefaultController::index' => ['privates', '.service_locator.3hxx.mU', 'get_ServiceLocator_3hxx_MUService.php', true],
    'App\\Controller\\DefaultController::manageBundle' => ['privates', '.service_locator.3hxx.mU', 'get_ServiceLocator_3hxx_MUService.php', true],
    'App\\Controller\\DefaultController::purchase' => ['privates', '.service_locator.3hxx.mU', 'get_ServiceLocator_3hxx_MUService.php', true],
    'App\\Controller\\DefaultController:index' => ['privates', '.service_locator.3hxx.mU', 'get_ServiceLocator_3hxx_MUService.php', true],
    'App\\Controller\\DefaultController:manageBundle' => ['privates', '.service_locator.3hxx.mU', 'get_ServiceLocator_3hxx_MUService.php', true],
    'App\\Controller\\DefaultController:purchase' => ['privates', '.service_locator.3hxx.mU', 'get_ServiceLocator_3hxx_MUService.php', true],
], [
    'App\\Controller\\DefaultController::index' => '?',
    'App\\Controller\\DefaultController::manageBundle' => '?',
    'App\\Controller\\DefaultController::purchase' => '?',
    'App\\Controller\\DefaultController:index' => '?',
    'App\\Controller\\DefaultController:manageBundle' => '?',
    'App\\Controller\\DefaultController:purchase' => '?',
]);
