<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'knpu.oauth2.client.google_main' shared service.

include_once $this->targetDirs[3].'/vendor/knpuniversity/oauth2-client-bundle/src/Client/OAuth2ClientInterface.php';
include_once $this->targetDirs[3].'/vendor/knpuniversity/oauth2-client-bundle/src/Client/OAuth2Client.php';
include_once $this->targetDirs[3].'/vendor/knpuniversity/oauth2-client-bundle/src/Client/Provider/GoogleClient.php';
include_once $this->targetDirs[3].'/vendor/league/oauth2-client/src/Tool/ArrayAccessorTrait.php';
include_once $this->targetDirs[3].'/vendor/league/oauth2-client/src/Tool/GuardedPropertyTrait.php';
include_once $this->targetDirs[3].'/vendor/league/oauth2-client/src/Tool/QueryBuilderTrait.php';
include_once $this->targetDirs[3].'/vendor/league/oauth2-client/src/Provider/AbstractProvider.php';
include_once $this->targetDirs[3].'/vendor/league/oauth2-client/src/Tool/BearerAuthorizationTrait.php';
include_once $this->targetDirs[3].'/vendor/league/oauth2-google/src/Provider/Google.php';

return $this->services['knpu.oauth2.client.google_main'] = new \KnpU\OAuth2ClientBundle\Client\Provider\GoogleClient(($this->privates['knpu.oauth2.provider_factory'] ?? $this->load('getKnpu_Oauth2_ProviderFactoryService.php'))->createProvider('League\\OAuth2\\Client\\Provider\\Google', ['clientId' => '492254723901-826bkfb708kmj8t7tqhasb88m6g3olr4.apps.googleusercontent.com', 'clientSecret' => 'lUKClGhFhEVXTsG1aty3NujP'], 'connect_google_check', [], []), ($this->services['request_stack'] ?? ($this->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())));
